### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by alberth8** [jquense/react-formal#125]
I'm trying to use Form.button so that I can validate only one group of fields within a Form component. 

```
                      <Form.Button
                        group="data"
                        component={ Button }
                        key="save"
                        type="button"
                        className="save"
                        onClick={ () => console.log('lol') }
                      >
                        Save
                      </Form.Button>,

```

All the Form.Field components that are relevant have the prop `group="data"` as well. 

But then I click on the button, I get an Uncaught TypeErorr, which in my bundle leads me to here:

```
	  split: function(path){
	    return path.match(SPLIT_REGEX)
	  }

```

Any idea how to fix this? I can't find any other way to selectively validate a form.

**Comment by alberth8** [comment]
@jquense Could you please advise on how I would validate a particular group of input fields within a form?

**Comment by jquense** [comment]
hey there, sorry. I believe I've fixed this bug in the most recent release can you confirm whether that's true or not?

**Comment by alberth8** [comment]
Is there a changelog? I don't see one. Just want to make sure there's no breaking changes from 0.23.0

**Comment by jquense** [comment]
No functional changelog.com at the moment but changes should be safe (I think)

**Comment by alberth8** [comment]
@jquense 

Thanks for the follow up. I've upgraded to 0.25.4, and when I have the type of Form.Button
```
                      <Form.Button
                        group="data"
                        key="save"
                        type="button"
                        component={ Button }
                        className="button"
                        onClick={ () => console.log('abc') }>
```

set to "button", I still get

> Uncaught TypeError: Cannot read property 'match' of undefined

All the Form.Field entries that I need to to be validated that are associated with this `group` are have the prop `group="data"`, and so does Form.Button.

**Comment by jquense** [comment]
Thanks, I'll take a look. Do you think you could put together a minimal reproduction that demonstrates the issue? It'll be easier to track down the bug
